import { useState } from "react";
import "./App.css";
import AddTask from "./component/AddTask";
import { FetchData } from "./component/FetchData";
import { Header } from "./component/Header";
import Tasks from "./component/Tasks";

// task state
function App() {
  const [taskItem, setTaskItem] = useState([
    {
      id: 1,
      text: "Doctors Appointment",
      day: "Feb %th at 2:30pm",
      reminder: false,
    },
    {
      id: 2,
      text: "Lunch Date",
      day: "Feb 14th at 2:30pm",
      reminder: false,
    },
    {
      id: 3,
      text: "Strategy Meeting",
      day: "Dec 20th at 12:30pm",
      reminder: false,
    },
  ]);
  // task state




  // add task
  const addTask = (task) => {
    // console.log(task);
    const id = Math.floor(Math.random() * 10000) + 1;
    const newTask = { id, ...task };
    setTaskItem([...taskItem, newTask]);
    console.log("added new task", id);
  };

  // delete task
  const deleteTask = (id) => {
    console.log("delete", id);
    // condition sets that if task.id(target item) is not equal to the index number generated by javascript/ filter while looping
    setTaskItem(taskItem.filter((task) => task.id !== id));
  };

  // toggle reminder
  const toggleReminder = (id) => {
    setTaskItem(
      taskItem.map((task) =>
        task.id === id ? { ...task, reminder: !task.reminder } : task
      )
    );
    console.log(id);
  };

  // tooggle add button
  const [showAddTask, setShowAddTask] = useState(false);
  return (
    <div className="App">
      <div className="tracker">
        <Header
          showAddTask={showAddTask}
          setShowAddTask={setShowAddTask}
          showClose={showAddTask}
        />

        {showAddTask && <AddTask onAdd={addTask} />}
        {taskItem.length > 0 ? (
          <Tasks
            tasks={taskItem}
            onDelete={deleteTask}
            onToggle={toggleReminder}
          />
        ) : (
          "No Tasks To Show"
        )}
      </div>
      <FetchData />
    </div>

  );
}

export default App;
